[2024-09-15 20:02:22,575] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:02:22,580] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:02:22,580] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:02:22,580] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:02:22,580] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:02:22,591] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-03 00:00:00+00:00
[2024-09-15 20:02:22,594] {standard_task_runner.py:52} INFO - Started process 11166 to run task
[2024-09-15 20:02:22,596] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpn58c73zv', '--error-file', '/tmp/tmpzpbowl74']
[2024-09-15 20:02:22,597] {standard_task_runner.py:80} INFO - Job 15: Subtask BRONZE_GOOG
[2024-09-15 20:02:22,625] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-03T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:02:22,664] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-03T00:00:00+00:00
[2024-09-15 20:02:23,226] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:02:23,230] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240103T000000, start_date=20240915T230222, end_date=20240915T230223
[2024-09-15 20:02:23,252] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:02:23,263] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:06:00,250] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:06:00,255] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:06:00,255] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:00,255] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:06:00,255] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:00,265] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-03 00:00:00+00:00
[2024-09-15 20:06:00,267] {standard_task_runner.py:52} INFO - Started process 11885 to run task
[2024-09-15 20:06:00,270] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp0yqi57c4', '--error-file', '/tmp/tmp4d_noou5']
[2024-09-15 20:06:00,270] {standard_task_runner.py:80} INFO - Job 17: Subtask BRONZE_GOOG
[2024-09-15 20:06:00,300] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-03T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:06:00,341] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-03T00:00:00+00:00
[2024-09-15 20:06:00,342] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/GOOG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:06:00,345] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240103T000000, start_date=20240915T230600, end_date=20240915T230600
[2024-09-15 20:06:00,355] {standard_task_runner.py:92} ERROR - Failed to execute job 17 for task BRONZE_GOOG ([Errno 13] Permission denied: '/datalake'; 11885)
[2024-09-15 20:06:00,363] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:06:00,375] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:08:46,266] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:08:46,271] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:08:46,271] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:08:46,271] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:08:46,271] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:08:46,282] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-03 00:00:00+00:00
[2024-09-15 20:08:46,284] {standard_task_runner.py:52} INFO - Started process 12479 to run task
[2024-09-15 20:08:46,287] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpie7_jr9a', '--error-file', '/tmp/tmpsk2u5xvr']
[2024-09-15 20:08:46,287] {standard_task_runner.py:80} INFO - Job 66: Subtask BRONZE_GOOG
[2024-09-15 20:08:46,316] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-03T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:08:46,357] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-03T00:00:00+00:00
[2024-09-15 20:08:46,923] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:08:46,928] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240103T000000, start_date=20240915T230846, end_date=20240915T230846
[2024-09-15 20:08:46,942] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:08:46,952] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:12:34,304] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:12:34,309] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:12:34,309] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:34,309] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:12:34,309] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:34,322] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-03 00:00:00+00:00
[2024-09-15 20:12:34,325] {standard_task_runner.py:52} INFO - Started process 13104 to run task
[2024-09-15 20:12:34,328] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpg11w5p6j', '--error-file', '/tmp/tmpzy6rqj_6']
[2024-09-15 20:12:34,328] {standard_task_runner.py:80} INFO - Job 66: Subtask BRONZE_GOOG
[2024-09-15 20:12:34,360] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-03T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:12:34,401] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-03T00:00:00+00:00
[2024-09-15 20:12:34,402] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake/GOOG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Documents'
[2024-09-15 20:12:34,404] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240103T000000, start_date=20240915T231234, end_date=20240915T231234
[2024-09-15 20:12:34,413] {standard_task_runner.py:92} ERROR - Failed to execute job 66 for task BRONZE_GOOG ([Errno 13] Permission denied: '/Documents'; 13104)
[2024-09-15 20:12:34,420] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:12:34,430] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:14:45,862] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:14:45,868] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:14:45,868] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:14:45,868] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:14:45,868] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:14:45,879] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-03 00:00:00+00:00
[2024-09-15 20:14:45,881] {standard_task_runner.py:52} INFO - Started process 13596 to run task
[2024-09-15 20:14:45,884] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpsx33xsug', '--error-file', '/tmp/tmpewx510tw']
[2024-09-15 20:14:45,884] {standard_task_runner.py:80} INFO - Job 66: Subtask BRONZE_GOOG
[2024-09-15 20:14:45,913] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-03T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:14:45,952] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-03T00:00:00+00:00
[2024-09-15 20:14:47,083] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:14:47,087] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240103T000000, start_date=20240915T231445, end_date=20240915T231447
[2024-09-15 20:14:47,103] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:14:47,113] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:15:45,584] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:15:45,589] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:15:45,589] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:15:45,589] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:15:45,589] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:15:45,601] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-03 00:00:00+00:00
[2024-09-15 20:15:45,603] {standard_task_runner.py:52} INFO - Started process 13754 to run task
[2024-09-15 20:15:45,606] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp3na3chus', '--error-file', '/tmp/tmpzvkplcxt']
[2024-09-15 20:15:45,607] {standard_task_runner.py:80} INFO - Job 66: Subtask BRONZE_GOOG
[2024-09-15 20:15:45,635] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-03T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:15:45,677] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-03T00:00:00+00:00
[2024-09-15 20:15:46,255] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:15:46,259] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240103T000000, start_date=20240915T231545, end_date=20240915T231546
[2024-09-15 20:15:46,303] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:15:46,333] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
