[2024-09-15 20:02:27,443] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2024-09-15 20:02:27,446] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2024-09-15 20:02:27,446] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:02:27,447] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:02:27,447] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:02:27,457] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-04 00:00:00+00:00
[2024-09-15 20:02:27,459] {standard_task_runner.py:52} INFO - Started process 11184 to run task
[2024-09-15 20:02:27,461] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-04T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpwy1udtgi', '--error-file', '/tmp/tmpwn0t_s4b']
[2024-09-15 20:02:27,462] {standard_task_runner.py:80} INFO - Job 17: Subtask BRONZE_AAPL
[2024-09-15 20:02:27,491] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-04T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:02:27,532] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-04T00:00:00+00:00
[2024-09-15 20:02:28,070] {history.py:244} ERROR - $AAPL: possibly delisted; no price data found  (1h 2024-01-03 -> 2024-01-03)
[2024-09-15 20:02:28,073] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:02:28,077] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240104T000000, start_date=20240915T230227, end_date=20240915T230228
[2024-09-15 20:02:28,118] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:02:28,128] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:06:04,079] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2024-09-15 20:06:04,084] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2024-09-15 20:06:04,084] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:04,084] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:06:04,084] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:04,095] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-04 00:00:00+00:00
[2024-09-15 20:06:04,097] {standard_task_runner.py:52} INFO - Started process 11903 to run task
[2024-09-15 20:06:04,099] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-04T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpf_u5x_3_', '--error-file', '/tmp/tmp73t_suj5']
[2024-09-15 20:06:04,099] {standard_task_runner.py:80} INFO - Job 19: Subtask BRONZE_AAPL
[2024-09-15 20:06:04,130] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-04T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:06:04,169] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-04T00:00:00+00:00
[2024-09-15 20:06:04,170] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/AAPL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:06:04,172] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240104T000000, start_date=20240915T230604, end_date=20240915T230604
[2024-09-15 20:06:04,181] {standard_task_runner.py:92} ERROR - Failed to execute job 19 for task BRONZE_AAPL ([Errno 13] Permission denied: '/datalake'; 11903)
[2024-09-15 20:06:04,192] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:06:04,202] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:08:51,273] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2024-09-15 20:08:51,279] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2024-09-15 20:08:51,279] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:08:51,279] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:08:51,279] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:08:51,291] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-04 00:00:00+00:00
[2024-09-15 20:08:51,294] {standard_task_runner.py:52} INFO - Started process 12497 to run task
[2024-09-15 20:08:51,296] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-04T00:00:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp1bgycsta', '--error-file', '/tmp/tmpkft83t_5']
[2024-09-15 20:08:51,296] {standard_task_runner.py:80} INFO - Job 68: Subtask BRONZE_AAPL
[2024-09-15 20:08:51,326] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-04T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:08:51,371] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-04T00:00:00+00:00
[2024-09-15 20:08:51,934] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:08:51,939] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240104T000000, start_date=20240915T230851, end_date=20240915T230851
[2024-09-15 20:08:51,952] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:08:51,962] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:12:38,149] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2024-09-15 20:12:38,155] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2024-09-15 20:12:38,155] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:38,155] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:12:38,155] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:38,170] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-04 00:00:00+00:00
[2024-09-15 20:12:38,172] {standard_task_runner.py:52} INFO - Started process 13124 to run task
[2024-09-15 20:12:38,175] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-04T00:00:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpcgg3ep89', '--error-file', '/tmp/tmplckoobms']
[2024-09-15 20:12:38,176] {standard_task_runner.py:80} INFO - Job 68: Subtask BRONZE_AAPL
[2024-09-15 20:12:38,212] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-04T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:12:38,261] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-04T00:00:00+00:00
[2024-09-15 20:12:38,262] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake/AAPL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Documents'
[2024-09-15 20:12:38,265] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240104T000000, start_date=20240915T231238, end_date=20240915T231238
[2024-09-15 20:12:38,276] {standard_task_runner.py:92} ERROR - Failed to execute job 68 for task BRONZE_AAPL ([Errno 13] Permission denied: '/Documents'; 13124)
[2024-09-15 20:12:38,309] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:12:38,321] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:14:50,423] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2024-09-15 20:14:50,427] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2024-09-15 20:14:50,427] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:14:50,427] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:14:50,427] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:14:50,438] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-04 00:00:00+00:00
[2024-09-15 20:14:50,441] {standard_task_runner.py:52} INFO - Started process 13614 to run task
[2024-09-15 20:14:50,443] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-04T00:00:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp4q143fbm', '--error-file', '/tmp/tmp3byw9cew']
[2024-09-15 20:14:50,443] {standard_task_runner.py:80} INFO - Job 68: Subtask BRONZE_AAPL
[2024-09-15 20:14:50,471] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-04T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:14:50,511] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-04T00:00:00+00:00
[2024-09-15 20:14:51,169] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:14:51,174] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240104T000000, start_date=20240915T231450, end_date=20240915T231451
[2024-09-15 20:14:51,220] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:14:51,231] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:15:50,611] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2024-09-15 20:15:50,615] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2024-09-15 20:15:50,615] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:15:50,615] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:15:50,615] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:15:50,626] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-04 00:00:00+00:00
[2024-09-15 20:15:50,629] {standard_task_runner.py:52} INFO - Started process 13774 to run task
[2024-09-15 20:15:50,631] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-04T00:00:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp89guvpoa', '--error-file', '/tmp/tmpv7esrxva']
[2024-09-15 20:15:50,631] {standard_task_runner.py:80} INFO - Job 68: Subtask BRONZE_AAPL
[2024-09-15 20:15:50,660] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-04T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:15:50,699] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-04T00:00:00+00:00
[2024-09-15 20:15:51,239] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:15:51,243] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240104T000000, start_date=20240915T231550, end_date=20240915T231551
[2024-09-15 20:15:51,287] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:15:51,315] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
