[2024-09-15 20:02:18,809] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:02:18,813] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:02:18,813] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:02:18,813] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:02:18,813] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:02:18,823] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-03 00:00:00+00:00
[2024-09-15 20:02:18,826] {standard_task_runner.py:52} INFO - Started process 11146 to run task
[2024-09-15 20:02:18,828] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpyfbqxgm7', '--error-file', '/tmp/tmp0lt5k2lf']
[2024-09-15 20:02:18,829] {standard_task_runner.py:80} INFO - Job 13: Subtask BRONZE_AAPL
[2024-09-15 20:02:18,858] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-03T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:02:18,897] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-03T00:00:00+00:00
[2024-09-15 20:02:19,463] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:02:19,469] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240103T000000, start_date=20240915T230218, end_date=20240915T230219
[2024-09-15 20:02:19,484] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:02:19,495] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:05:57,556] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:05:57,563] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:05:57,563] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:05:57,563] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:05:57,563] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:05:57,585] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-03 00:00:00+00:00
[2024-09-15 20:05:57,589] {standard_task_runner.py:52} INFO - Started process 11867 to run task
[2024-09-15 20:05:57,592] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpahc9zbrm', '--error-file', '/tmp/tmppza8x8bq']
[2024-09-15 20:05:57,593] {standard_task_runner.py:80} INFO - Job 15: Subtask BRONZE_AAPL
[2024-09-15 20:05:57,633] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-03T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:05:57,688] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-03T00:00:00+00:00
[2024-09-15 20:05:57,689] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/AAPL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:05:57,691] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240103T000000, start_date=20240915T230557, end_date=20240915T230557
[2024-09-15 20:05:57,699] {standard_task_runner.py:92} ERROR - Failed to execute job 15 for task BRONZE_AAPL ([Errno 13] Permission denied: '/datalake'; 11867)
[2024-09-15 20:05:57,726] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:05:57,736] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:08:41,601] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:08:41,605] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:08:41,605] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:08:41,605] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:08:41,605] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:08:41,615] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-03 00:00:00+00:00
[2024-09-15 20:08:41,618] {standard_task_runner.py:52} INFO - Started process 12461 to run task
[2024-09-15 20:08:41,620] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpe_w63lp8', '--error-file', '/tmp/tmpooszbr6x']
[2024-09-15 20:08:41,621] {standard_task_runner.py:80} INFO - Job 64: Subtask BRONZE_AAPL
[2024-09-15 20:08:41,649] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-03T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:08:41,688] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-03T00:00:00+00:00
[2024-09-15 20:08:42,324] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:08:42,329] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240103T000000, start_date=20240915T230841, end_date=20240915T230842
[2024-09-15 20:08:42,357] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:08:42,366] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:12:31,260] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:12:31,265] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:12:31,265] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:31,265] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:12:31,265] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:31,276] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-03 00:00:00+00:00
[2024-09-15 20:12:31,279] {standard_task_runner.py:52} INFO - Started process 13084 to run task
[2024-09-15 20:12:31,281] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp1_j2f69z', '--error-file', '/tmp/tmpsfr3i874']
[2024-09-15 20:12:31,282] {standard_task_runner.py:80} INFO - Job 64: Subtask BRONZE_AAPL
[2024-09-15 20:12:31,309] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-03T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:12:31,349] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-03T00:00:00+00:00
[2024-09-15 20:12:31,350] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake/AAPL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Documents'
[2024-09-15 20:12:31,352] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240103T000000, start_date=20240915T231231, end_date=20240915T231231
[2024-09-15 20:12:31,361] {standard_task_runner.py:92} ERROR - Failed to execute job 64 for task BRONZE_AAPL ([Errno 13] Permission denied: '/Documents'; 13084)
[2024-09-15 20:12:31,374] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:12:31,384] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:14:40,497] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:14:40,501] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:14:40,501] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:14:40,501] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:14:40,502] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:14:40,512] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-03 00:00:00+00:00
[2024-09-15 20:14:40,514] {standard_task_runner.py:52} INFO - Started process 13575 to run task
[2024-09-15 20:14:40,516] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpoj0krpgz', '--error-file', '/tmp/tmp1ip26jrk']
[2024-09-15 20:14:40,517] {standard_task_runner.py:80} INFO - Job 64: Subtask BRONZE_AAPL
[2024-09-15 20:14:40,546] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-03T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:14:40,588] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-03T00:00:00+00:00
[2024-09-15 20:14:41,856] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:14:41,862] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240103T000000, start_date=20240915T231440, end_date=20240915T231441
[2024-09-15 20:14:41,898] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:14:41,911] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:15:41,714] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:15:41,719] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-09-15 20:15:41,719] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:15:41,719] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:15:41,719] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:15:41,731] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-03 00:00:00+00:00
[2024-09-15 20:15:41,734] {standard_task_runner.py:52} INFO - Started process 13736 to run task
[2024-09-15 20:15:41,737] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpzbv9ucef', '--error-file', '/tmp/tmppf8ulv2d']
[2024-09-15 20:15:41,738] {standard_task_runner.py:80} INFO - Job 64: Subtask BRONZE_AAPL
[2024-09-15 20:15:41,770] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-03T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:15:41,814] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-03T00:00:00+00:00
[2024-09-15 20:15:42,379] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:15:42,383] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240103T000000, start_date=20240915T231541, end_date=20240915T231542
[2024-09-15 20:15:42,433] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:15:42,444] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
