[2024-09-15 20:02:45,295] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:02:45,299] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:02:45,299] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:02:45,300] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:02:45,300] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:02:45,310] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-05 00:00:00+00:00
[2024-09-15 20:02:45,312] {standard_task_runner.py:52} INFO - Started process 11239 to run task
[2024-09-15 20:02:45,315] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp27s83xjo', '--error-file', '/tmp/tmpzumrk1hk']
[2024-09-15 20:02:45,315] {standard_task_runner.py:80} INFO - Job 23: Subtask BRONZE_GOOG
[2024-09-15 20:02:45,342] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-05T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:02:45,381] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-05T00:00:00+00:00
[2024-09-15 20:02:48,568] {history.py:244} ERROR - $GOOG: possibly delisted; no price data found  (1h 2024-01-04 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1704344400, endDate = 1704258000")
[2024-09-15 20:02:48,576] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:02:48,586] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240105T000000, start_date=20240915T230245, end_date=20240915T230248
[2024-09-15 20:02:48,636] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:02:48,645] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:06:12,618] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:06:12,624] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:06:12,624] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:12,624] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:06:12,624] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:12,635] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-05 00:00:00+00:00
[2024-09-15 20:06:12,638] {standard_task_runner.py:52} INFO - Started process 11959 to run task
[2024-09-15 20:06:12,640] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpvfsq4aio', '--error-file', '/tmp/tmpualsglyy']
[2024-09-15 20:06:12,641] {standard_task_runner.py:80} INFO - Job 25: Subtask BRONZE_GOOG
[2024-09-15 20:06:12,672] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-05T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:06:12,711] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-05T00:00:00+00:00
[2024-09-15 20:06:12,712] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/GOOG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:06:12,714] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240105T000000, start_date=20240915T230612, end_date=20240915T230612
[2024-09-15 20:06:12,723] {standard_task_runner.py:92} ERROR - Failed to execute job 25 for task BRONZE_GOOG ([Errno 13] Permission denied: '/datalake'; 11959)
[2024-09-15 20:06:12,733] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:06:12,743] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:09:03,641] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:09:03,647] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:09:03,647] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:09:03,647] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:09:03,647] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:09:03,657] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-05 00:00:00+00:00
[2024-09-15 20:09:03,660] {standard_task_runner.py:52} INFO - Started process 12551 to run task
[2024-09-15 20:09:03,662] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp7jp84nme', '--error-file', '/tmp/tmpw9fwhcg1']
[2024-09-15 20:09:03,662] {standard_task_runner.py:80} INFO - Job 74: Subtask BRONZE_GOOG
[2024-09-15 20:09:03,691] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-05T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:09:03,732] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-05T00:00:00+00:00
[2024-09-15 20:09:04,274] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:09:04,278] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240105T000000, start_date=20240915T230903, end_date=20240915T230904
[2024-09-15 20:09:04,317] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:09:04,327] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:12:47,357] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:12:47,362] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:12:47,362] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:47,362] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:12:47,362] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:47,373] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-05 00:00:00+00:00
[2024-09-15 20:12:47,375] {standard_task_runner.py:52} INFO - Started process 13178 to run task
[2024-09-15 20:12:47,377] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpal3odtxm', '--error-file', '/tmp/tmpn14i83_1']
[2024-09-15 20:12:47,378] {standard_task_runner.py:80} INFO - Job 74: Subtask BRONZE_GOOG
[2024-09-15 20:12:47,405] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-05T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:12:47,446] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-05T00:00:00+00:00
[2024-09-15 20:12:47,447] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake/GOOG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Documents'
[2024-09-15 20:12:47,449] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240105T000000, start_date=20240915T231247, end_date=20240915T231247
[2024-09-15 20:12:47,466] {standard_task_runner.py:92} ERROR - Failed to execute job 74 for task BRONZE_GOOG ([Errno 13] Permission denied: '/Documents'; 13178)
[2024-09-15 20:12:47,470] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:12:47,480] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:15:02,939] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:15:02,945] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:15:02,945] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:15:02,945] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:15:02,945] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:15:02,956] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-05 00:00:00+00:00
[2024-09-15 20:15:02,958] {standard_task_runner.py:52} INFO - Started process 13674 to run task
[2024-09-15 20:15:02,961] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpx_v699ji', '--error-file', '/tmp/tmpggonljyi']
[2024-09-15 20:15:02,961] {standard_task_runner.py:80} INFO - Job 74: Subtask BRONZE_GOOG
[2024-09-15 20:15:02,992] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-05T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:15:03,035] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-05T00:00:00+00:00
[2024-09-15 20:15:03,561] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:15:03,566] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240105T000000, start_date=20240915T231502, end_date=20240915T231503
[2024-09-15 20:15:03,617] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:15:03,635] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:16:02,422] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:16:02,427] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-09-15 20:16:02,428] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:16:02,428] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:16:02,428] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:16:02,442] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-05 00:00:00+00:00
[2024-09-15 20:16:02,445] {standard_task_runner.py:52} INFO - Started process 13830 to run task
[2024-09-15 20:16:02,447] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpp0r2u2ov', '--error-file', '/tmp/tmpwv3rcek7']
[2024-09-15 20:16:02,448] {standard_task_runner.py:80} INFO - Job 74: Subtask BRONZE_GOOG
[2024-09-15 20:16:02,476] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-05T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:16:02,517] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-05T00:00:00+00:00
[2024-09-15 20:16:03,073] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:16:03,077] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240105T000000, start_date=20240915T231602, end_date=20240915T231603
[2024-09-15 20:16:03,103] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:16:03,112] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
