[2024-09-15 20:03:00,818] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:03:00,822] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:03:00,822] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:03:00,822] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:03:00,822] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:03:00,833] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:03:00,835] {standard_task_runner.py:52} INFO - Started process 11268 to run task
[2024-09-15 20:03:00,837] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpblf7ctfx', '--error-file', '/tmp/tmp_7qhgt3s']
[2024-09-15 20:03:00,838] {standard_task_runner.py:80} INFO - Job 26: Subtask BRONZE_MSFT
[2024-09-15 20:03:00,864] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:03:00,902] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:03:04,574] {history.py:244} ERROR - $MSFT: possibly delisted; no price data found  (1h 2024-01-05 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1704430800, endDate = 1704258000")
[2024-09-15 20:03:04,577] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:03:04,582] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240106T000000, start_date=20240915T230300, end_date=20240915T230304
[2024-09-15 20:03:04,598] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:03:04,609] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:06:17,518] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:06:17,523] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:06:17,523] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:17,523] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:06:17,523] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:17,533] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:06:17,535] {standard_task_runner.py:52} INFO - Started process 11988 to run task
[2024-09-15 20:06:17,537] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmph8_dlbep', '--error-file', '/tmp/tmpbbrj7tss']
[2024-09-15 20:06:17,538] {standard_task_runner.py:80} INFO - Job 28: Subtask BRONZE_MSFT
[2024-09-15 20:06:17,565] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:06:17,602] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:06:17,603] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/MSFT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:06:17,606] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240106T000000, start_date=20240915T230617, end_date=20240915T230617
[2024-09-15 20:06:17,614] {standard_task_runner.py:92} ERROR - Failed to execute job 28 for task BRONZE_MSFT ([Errno 13] Permission denied: '/datalake'; 11988)
[2024-09-15 20:06:17,630] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:06:17,645] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:09:09,715] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:09:09,720] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:09:09,720] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:09:09,720] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:09:09,720] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:09:09,731] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:09:09,733] {standard_task_runner.py:52} INFO - Started process 12579 to run task
[2024-09-15 20:09:09,735] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpsjokmoms', '--error-file', '/tmp/tmps37i195m']
[2024-09-15 20:09:09,736] {standard_task_runner.py:80} INFO - Job 77: Subtask BRONZE_MSFT
[2024-09-15 20:09:09,764] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:09:09,807] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:09:10,365] {history.py:244} ERROR - $MSFT: possibly delisted; no price data found  (1h 2024-01-03 -> 2024-01-03)
[2024-09-15 20:09:10,368] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:09:10,372] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240106T000000, start_date=20240915T230909, end_date=20240915T230910
[2024-09-15 20:09:10,391] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:09:10,401] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:12:51,880] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:12:51,885] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:12:51,885] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:51,885] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:12:51,885] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:51,896] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:12:51,899] {standard_task_runner.py:52} INFO - Started process 13208 to run task
[2024-09-15 20:12:51,901] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpglzvwv3l', '--error-file', '/tmp/tmpgls_3yox']
[2024-09-15 20:12:51,902] {standard_task_runner.py:80} INFO - Job 77: Subtask BRONZE_MSFT
[2024-09-15 20:12:51,930] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:12:51,969] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:12:51,970] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake/MSFT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Documents'
[2024-09-15 20:12:51,973] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240106T000000, start_date=20240915T231251, end_date=20240915T231251
[2024-09-15 20:12:51,983] {standard_task_runner.py:92} ERROR - Failed to execute job 77 for task BRONZE_MSFT ([Errno 13] Permission denied: '/Documents'; 13208)
[2024-09-15 20:12:51,994] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:12:52,004] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:16:08,760] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:16:08,764] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-09-15 20:16:08,765] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:16:08,765] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:16:08,765] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:16:08,776] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-06 00:00:00+00:00
[2024-09-15 20:16:08,779] {standard_task_runner.py:52} INFO - Started process 13860 to run task
[2024-09-15 20:16:08,781] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp_jre0auy', '--error-file', '/tmp/tmplaeq4ihx']
[2024-09-15 20:16:08,781] {standard_task_runner.py:80} INFO - Job 77: Subtask BRONZE_MSFT
[2024-09-15 20:16:08,812] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-06T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:16:08,855] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-06T00:00:00+00:00
[2024-09-15 20:16:09,504] {history.py:244} ERROR - $MSFT: possibly delisted; no price data found  (1h 2024-01-03 -> 2024-01-03)
[2024-09-15 20:16:09,511] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:16:09,519] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240106T000000, start_date=20240915T231608, end_date=20240915T231609
[2024-09-15 20:16:09,558] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:16:09,569] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
